### ISSUE TITLE
`rvc status --json` does not show all connections

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rvc#88] opened 2017-09-06 10:04 UTC
`rvc status` shows all connections, but `rvc status --json` doesn't.

**Comment by erikbor** [comment] 2017-09-07 02:14
@ronaldtse that's because of the syntax of `rvc`: `rvc status <VPN NAME>` so in your case `rvc` showed the status of a VPN named `--json` which does not exist and therefor shows `code 4`.
VPN names with hypens `-` are allowed.

**Comment by ronaldtse** [comment] 2017-09-07 02:18
It is convention in many tools that `--json` would provide JSON output.

Aside from why hyphens are allowed as initials, `--json` is obviously (to a user) an "option" and must never be the name of a VPN connection -- that's confusing as hell...

**Comment by erikbor** [comment] 2017-09-07 02:26
The option `--json` is not part of `rvc status` right now so it's expected behaviour.

@jjr840430 can you implement that `rvc` by default displays a table (as requested in [90](https://github.com/riboseinc/rvc/issues/90)) and accept `--json` for **every** option.

**Comment by ronaldtse** [comment] 2017-09-07 03:41
Thanks @erikbor @jjr840430 !

**Comment by jjr840430** [comment] 2017-09-07 05:23
@erikbor OK, I will implement.

**Comment by jjr840430** [comment] 2017-09-07 09:40
fixed on #98

**Closed by jjr840430** 2017-09-07 09:40 UTC
